[tool.poetry]
name = "otimizacao"
version = "1.0"
description = ""
authors = ["notPlancha <andre.plancha@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pulp = "^2.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
